### ISSUE TITLE
Unable to delete a project

### ISSUE THREAD

**Issue by pdorio** [gisclient/gisclient-3#17]
SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "field" does not exist
LINE 1: delete from field where relation_id=old.relation_id
^
QUERY: delete from field where relation_id=old.relation_id
CONTEXT: PL/pgSQL function "delete_relation" line 3 at SQL statement

**Comment by robystar** [comment]
In db > trigger functions > delete_relation add schema name to field

delete from gisclient_34.field where relation_id=old.relation_id;
