### ISSUE TITLE
Autenticazione dalla pagina /author/admin/ non funziona

### ISSUE THREAD

**Issue by pdorio** [gisclient/gisclient-3#22]
![2015-08-19_09h38_43](https://cloud.githubusercontent.com/assets/3297563/9351066/57590878-4656-11e5-9b7b-65d587268ad0.png)
Autenticazione dalla pagina /author/admin/ non funziona.

Vedi allegato. Nessun log

**Comment by robystar** [comment]
avevo modificato il file index.php per postare la pwd in md5. Probabilmente
nel merge ha aggiornato anche il master. l'ho sistemato

2015-08-19 9:39 GMT+02:00 pdorio notifications@github.com:

**Comment by pdorio** [comment]
Verificato, il problema è sistemato. chiudo!
