### ISSUE TITLE
Errore nell'extent del layer scritto nel mapfile

### ISSUE THREAD

**Issue by pdorio** [gisclient/gisclient-3#60]
L'extent del layer scritto sul mapfile è attualmente quello di mappa. tuttavia tale extent deve essere nello stesso sistema di riferimento del layer altrimenti non funziona la riproiezione

**Comment by robystar** [comment]
da verificare perchè ovviamente era così

2016-03-21 11:48 GMT+01:00 pdorio notifications@github.com:
