### ISSUE TITLE
export of theme or project is broken

### ISSUE THREAD

**Issue by ddegasperi** [gisclient/gisclient-3#7]
The export of a theme does not write information about:
- catalog reference in the @FOREIGNKEY (see INSERT INTO layer)
- relation reference in the @FOREIGNKEY (see INSERT INTO field)

Seems a problem of the content present in e_level or e_form

**Comment by robystar** [comment]
Fixed

**Comment by pdorio** [comment]
The import of a project is broken on the mapset. I think there are more field as inserts:

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "3-signs" CONTEXT: SQL statement "select map||(max(newindex)+1)::varchar from (select regexp_replace(mapset_name,'([0-9]+)$','') as map,case when(regexp_replace(mapset_name,'^([A-z_]+)','')='') then 0 else regexp_replace(mapset_name,'^([A-z_]+)','')::integer end as newindex from gisclient_34.mapset where 'r3-signs' ~\* regexp_replace(mapset_name,'([0-9]+)$','')) X group by map;" PL/pgSQL function "new_pkey_varchar" line 11 at EXECUTE statement' in /data/sites/gc/author-34/public/admin/lib/export.php:141 Stack trace: #0 /data/sites/gc/author-34/public/admin/lib/export.php(141): PDO->query('select gisclien...') #1 /data/sites/gc/author-34/public/admin/include/import.php(70): import('/data/sites/gc/...', '0', 'test', 'test', NULL) #2 /data/sites/gc/author-34/public/admin/lib/page.class.php(1014): include('/data/sites/gc/...') #3 /data/sites/gc/author-34/public/admin/index.php( in /data/sites/gc/author-34/public/admin/lib/export.php on line 141

**Comment by robystar** [comment]
Fixed 
mapset_name = project_name||mapset_name in new project from import
